test('mening ilk testim', () => { 
    throw new Error('nimadir ishlamay  qoldiku shuning uchun xatolikga uchradi')
 })